
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaovpoglmajzuamapxzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhb3Zwb2dsbWFqenVhbWFweHptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDc0MTUsImV4cCI6MjA1OTYyMzQxNX0.kkCNdrpHi6bjYUL9CMATIk_FkS6SBGg4BVYz0Bn6i-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
